<a href="https://colab.research.google.com/github/Sultonmahmudov/week1-lab201/blob/main/Week3_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [1]:
import torch

# TODO: Create a scalar tensor
scalar = torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [2]:
# TODO: Create a vector tensor
vector = torch.tensor([1, 2, 3, 4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [3]:
# TODO: Create a matrix tensor
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [4]:
# TODO: Create a 3D tensor
tensor_3d = torch.rand(size=(2, 2, 2))

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[0.8605, 0.6109],
         [0.7804, 0.1028]],

        [[0.3378, 0.4946],
         [0.6783, 0.5972]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [5]:
# TODO: Create random tensor
random_tensor = torch.rand(4, 4)

# Print details

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.5627, 0.7314, 0.6695, 0.6781],
        [0.4921, 0.0759, 0.5694, 0.6215],
        [0.5687, 0.7306, 0.2967, 0.6065],
        [0.9301, 0.4939, 0.3667, 0.2841]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [6]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(size=(3, 224, 224))

# Print details
print(image_tensor)

print(f"Shape: {image_tensor.shape}")

tensor([[[0.1870, 0.9953, 0.6532,  ..., 0.7320, 0.1002, 0.0886],
         [0.2130, 0.8690, 0.7412,  ..., 0.7563, 0.4116, 0.3409],
         [0.6561, 0.5451, 0.0260,  ..., 0.1204, 0.7447, 0.5183],
         ...,
         [0.0594, 0.0733, 0.6717,  ..., 0.7000, 0.4623, 0.0720],
         [0.5983, 0.3419, 0.0547,  ..., 0.8121, 0.8773, 0.1759],
         [0.9547, 0.0998, 0.6191,  ..., 0.5651, 0.1053, 0.1678]],

        [[0.9100, 0.1908, 0.2202,  ..., 0.2384, 0.7534, 0.0551],
         [0.7342, 0.7992, 0.5962,  ..., 0.1047, 0.6237, 0.6312],
         [0.3658, 0.1389, 0.4733,  ..., 0.2392, 0.2930, 0.3228],
         ...,
         [0.8482, 0.0863, 0.7942,  ..., 0.8769, 0.8285, 0.5641],
         [0.4474, 0.6071, 0.3331,  ..., 0.3981, 0.2888, 0.0646],
         [0.3303, 0.0458, 0.4438,  ..., 0.8950, 0.0169, 0.9216]],

        [[0.1374, 0.6964, 0.1602,  ..., 0.9647, 0.8741, 0.7547],
         [0.5401, 0.9907, 0.5052,  ..., 0.9030, 0.5430, 0.1629],
         [0.6021, 0.4056, 0.4150,  ..., 0.5295, 0.3730, 0.

## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [7]:
# TODO: Create zeros tensor
zeros = torch.zeros_like(image_tensor)

# Print details
print(zeros)

print(f"Shape: {zeros.shape}")

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])
Shape: torch.Size([3, 224, 224])


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [9]:
random_tensor = torch.rand(3, 3)
# TODO: Create ones like
ones_like = torch.ones_like(random_tensor)

# Print details
print(ones_like)

print(f"Shape: {ones_like.shape}")

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Shape: torch.Size([3, 3])


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [10]:
# TODO: Create range tensor
range_tensor = torch.arange(0, 21, 2)

# Print details
print(range_tensor)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [13]:
# TODO: float16 tensor
float16_tensor = torch.tensor([1.0,2.0,3.0],dtype=torch.float16)

# TODO: int64 tensor
int64_tensor = torch.tensor([1.0,2.0,3.0],dtype=torch.int64)

### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [14]:
# TODO: Change dtype
float32_tensor = torch.tensor(float16_tensor,dtype=torch.float32)

/tmp/ipython-input-701622923.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  float32_tensor = torch.tensor(float16_tensor,dtype=torch.float32)


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [15]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2,3,4)

print(info_tensor)
print(f"Shape: {info_tensor.shape}")
print(f"Datatype: {info_tensor.dtype}")
print(f"Device: {info_tensor.device}")


tensor([[[0.6759, 0.1588, 0.0012, 0.9780],
         [0.8445, 0.9362, 0.2432, 0.9190],
         [0.0886, 0.6894, 0.2781, 0.8187]],

        [[0.7004, 0.3167, 0.9304, 0.3702],
         [0.5906, 0.4461, 0.9400, 0.6803],
         [0.0488, 0.4083, 0.0213, 0.8002]]])
Shape: torch.Size([2, 3, 4])
Datatype: torch.float32
Device: cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [18]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
print(tensor + 5)
# TODO: Subtract 10
print(tensor - 10)
# TODO: Multiply by 2
print(tensor * 2)
# TODO: Divide by 10
print(tensor / 10)

tensor([15, 25, 35])
tensor([ 0, 10, 20])
tensor([20, 40, 60])
tensor([1., 2., 3.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [22]:
# TODO: Create A and B
A = torch.tensor([[1,2,3],[4,5,6]])
B = torch.tensor([[7,8],[9,10],[11,12]])

# TODO: Matrix mul using torch.mm
result_mm = torch.mm(A,B)
resylt_mm = torch.mm(B,A)
print(result_mm)
print(result_mm.shape)

# TODO: Matrix mul using @
result_at = A @ B
print(result_at)
print(result_at.shape)

tensor([[ 58,  64],
        [139, 154]])
torch.Size([2, 2])
tensor([[ 58,  64],
        [139, 154]])
torch.Size([2, 2])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [25]:
agg_tensor = torch.arange(0, 101)
# TODO: Min
print(torch.min(agg_tensor))
# TODO: Max
print(torch.max(agg_tensor))
# TODO: Mean (note: may need to cast to float)
print(torch.mean(agg_tensor.type(torch.float32)))
# TODO: Sum

tensor(0)
tensor(100)
tensor(50.)


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [26]:
# TODO: Argmin
print(torch.argmin(agg_tensor))
# TODO: Argmax
print(torch.argmax(agg_tensor))

tensor(0)
tensor(100)


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [27]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = torch.reshape(reshape_tensor,(2,5))
print(reshaped)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [28]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
print(torch.stack([tensor1, tensor2],dim=0))
# TODO: Stack horizontally (dim=1)
print(torch.stack([tensor1, tensor2],dim=1))

tensor([[[0.3829, 0.6442],
         [0.2364, 0.4718]],

        [[0.9617, 0.8768],
         [0.1936, 0.2059]]])
tensor([[[0.3829, 0.6442],
         [0.9617, 0.8768]],

        [[0.2364, 0.4718],
         [0.1936, 0.2059]]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [30]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed = torch.squeeze(squeeze_tensor)
print(squeezed)

# TODO: Unsqueeze on dim=0
unsqueezed = torch.unsqueeze(squeezed,dim=0)
print(unsqueezed)

tensor([0.9081, 0.8359, 0.7252])
tensor([[0.9081, 0.8359, 0.7252]])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [31]:
image_tensor = torch.rand(3, 100, 100)
# TODO: Permute
permuted = torch.permute(image_tensor,(1,2,0))
print(permuted)

tensor([[[0.5316, 0.3449, 0.9908],
         [0.8384, 0.7490, 0.6199],
         [0.2573, 0.7217, 0.1833],
         ...,
         [0.0221, 0.8456, 0.1157],
         [0.9041, 0.3080, 0.2901],
         [0.5601, 0.9734, 0.9461]],

        [[0.4739, 0.9185, 0.2877],
         [0.1492, 0.3117, 0.7142],
         [0.1302, 0.4644, 0.2238],
         ...,
         [0.4225, 0.3572, 0.9246],
         [0.6098, 0.5614, 0.1650],
         [0.0900, 0.6757, 0.0580]],

        [[0.2186, 0.6291, 0.4912],
         [0.6723, 0.7473, 0.2146],
         [0.9017, 0.7120, 0.4009],
         ...,
         [0.3842, 0.5899, 0.2040],
         [0.0277, 0.1034, 0.2789],
         [0.5682, 0.7656, 0.1482]],

        ...,

        [[0.7753, 0.9110, 0.6879],
         [0.1198, 0.0260, 0.7914],
         [0.1338, 0.6341, 0.9862],
         ...,
         [0.4384, 0.6789, 0.6297],
         [0.9469, 0.9743, 0.3217],
         [0.0259, 0.5231, 0.0144]],

        [[0.2185, 0.6851, 0.5014],
         [0.9618, 0.0081, 0.7201],
         [0.

## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [41]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5
print(f"Get 5 :{index_tensor[0][1][1]}")
# TODO: Get second row [4,5,6]
print(f"Get second row :{index_tensor[0][1]}")

Get 5 :5
Get second row :tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [42]:
import numpy as np
numpy_array = np.array([1,2,3,4])
# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)
print(from_numpy)

tensor([1, 2, 3, 4])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [44]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy = tensor.numpy(pytorch_tensor)
print(to_numpy)

TypeError: numpy() takes 0 positional arguments but 1 was given

## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [ ]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)

# TODO: Reset seed for second tensor

rand2 = torch.rand(2,2)

# Check equality
print(rand1 == rand2)

## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [ ]:
# TODO: Set device
device =

### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [ ]:
gpu_tensor = torch.tensor([10, 20, 30])
# TODO: Move to device
gpu_tensor =

# TODO: Move back to CPU and to NumPy
cpu_numpy =